### PR TITLE
Module update

### PR DESCRIPTION
**Pull request by b4dnewz**
Hi, first of all, thanks for the module and for the great idea.

I've cleared some unused deps and updated the rest of them and all the code. 
Also switched to `jest `instead of `mocha` which has some features included in the core such code coverage.

I've cleaned up a little bit the project and updated the readme file. enabled travis check for node LTS version 6 and coveralls reports.

Also the first time I tried it wasn't working, I fixed it by using `os.EOL` variable to split the dictionary files, like this shouldn't bug anymore in any device.

Let me know if you are interested to merge my PR otherwise I will create another module since i'm using this functionality in one of my projects.

### CODE REVIEW

**Comment by b4dnewz** [comment]
Sorry for the frequent commits, I'm using **snyk** globally and authenticated and I didn't realize without the authorization (like in the travis server for example) will not work.

Now with **nsp** is pretty much doing the same and it's working.

**Comment by skepticfx** [comment]
@b4dnewz Thanks for the great work. This project has been not so active for some time and haven't got the time to look into things.

**Comment by skepticfx** [comment]
@b4dnewz Updated the NPM package too. Its 1.3.0.

Let know if you want to be added as a contributor to this project. I'd love to add.

**Comment by b4dnewz** [comment]
Hi @skepticfx, thanks for been so quick to answer!

>This project has been not so active for some time and haven't got the time to look into things.

Did you found other projects or simply you hadn't enough time to dedicate to it?

>Let know if you want to be added as a collaborator to this project

Yes, I would like, thank you!

By the way I'm using your package in a project called [domain-scanner](https://github.com/b4dnewz/domain-scanner) which scans a domain for various things and from yesterday, subdomains too.. so I will actively both of them in my spare time.

**Comment by skepticfx** [comment]
Cool! 👍 Added you as a collaborator.

**Pull request merged**
